### ISSUE TITLE
running webui-monitor fails

### ISSUE THREAD

**Issue by pochadri** [kamkie/mikro-service-example#2]
Running webui-monitor fails.

the reason is it is trying to start the spring-boot-admin-samples spring boot project which is not present.

did you miss adding that project to git?

**Comment by kamkie** [comment]
i changed spring-boot-admin-samples to service-monitor
for now test will fail if service config will not be running in background

i need to make default configs for test to allow that 
maybe spring `test` profile

also in webui-monitor pom line 39 `executable` is platform specific  
for unix like systems remove .cmd

**Comment by pochadri** [comment]
thanks for checking

may be we should create a generator for microservices infrastructure in the lines of jhipster project.
also check the project https://github.com/VanRoy/spring-cloud-dashboard

**Comment by kamkie** [comment]
I seen https://github.com/VanRoy/spring-cloud-dashboard yesterday 
I also want to include hysteria dashboard in admin panel 

admin panel that i currently use is from https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-server-ui and only reason is that inside my repo is because `spring-boot-admin-server-ui` is not published to maven 

today i will check if i can easily switch panels
